# Generated by Django 2.2.6 on 2019-10-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
