# Generated by Django 2.2.6 on 2019-10-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191007_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
