# Generated by Django 2.2.6 on 2019-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
